server {
    listen 80;
    listen [::]:80;
    server_name vps-c79afd97.vps.ovh.ca;
    location ^~ /.well-known/acme-challenge/ { root /srv/iqtadi/acme; }
    location / { return 301 https://vps-c79afd97.vps.ovh.ca$request_uri; }
}
