"""Arabic prayer guidance generated by DeepSeek (`deepseek-flash`).

Scope and guardrails
--------------------
The on-device prayer engine owns progression: it advances stations
deterministically from pose observations and never waits on this route. This
module only turns a small structured summary of the current session into one
short Arabic encouragement/instruction sentence.

* No camera frames, keypoints, video or images ever reach this route. The
  request body is a handful of enum/number fields describing state.
* The prompt forbids religious verdicts: the model must not rule on the
  validity or acceptance of a prayer, and must not issue fatwa-style claims.
* Nothing is persisted. Results are memoised in-process only, keyed by
  (prayer, station, event), to bound paid calls.
* Any failure degrades to bundled static Arabic text with `degraded=true`
  rather than returning an error, because the client must never be blocked.
"""

from __future__ import annotations

import logging
import threading
from typing import Literal

from fastapi import APIRouter
from pydantic import BaseModel, Field

from ..config import get_settings
from ..llm.deepseek_client import LLMNotConfigured, get_deepseek_client

logger = logging.getLogger(__name__)

router = APIRouter(tags=["prayer guidance"])

# Six core stations per rak'ah. Kept byte-identical to
# `admin.prayer_references.STATIONS` so the reference editor and the guidance
# vocabulary cannot drift; `tests/test_prayer_guidance.py` enforces that.
CORE_STATIONS = (
    "standing",
    "ruku",
    "standing_after_ruku",
    "sujood_first",
    "sitting",
    "sujood_second",
)
# Sittings that exist in the Flutter prayer engine but are not reference-editor
# segments.
EXTRA_STATIONS = ("intermediate_sitting", "final_sitting")
STATIONS = CORE_STATIONS + EXTRA_STATIONS

PRAYERS = ("fajr", "dhuhr", "asr", "maghrib", "isha", "demo")
EVENTS = ("start", "retry", "uncertain", "completed", "stopped")

STATION_AR = {
    "standing": "القيام",
    "ruku": "الركوع",
    "standing_after_ruku": "الاعتدال بعد الركوع",
    "sujood_first": "السجود الأول",
    "sitting": "الجلسة بين السجدتين",
    "sujood_second": "السجود الثاني",
    "intermediate_sitting": "الجلسة الوسطى",
    "final_sitting": "الجلسة الأخيرة",
}

PRAYER_AR = {
    "fajr": "الفجر",
    "dhuhr": "الظهر",
    "asr": "العصر",
    "maghrib": "المغرب",
    "isha": "العشاء",
    "demo": "ركعة تجريبية",
}

EVENT_AR = {
    "start": "بدء الجلسة",
    "retry": "إعادة المحاولة",
    "uncertain": "الوضعية غير واضحة",
    "completed": "إتمام الحركات",
    "stopped": "إيقاف الجلسة",
}

# Served when the LLM is unavailable. Deliberately free of any religious
# ruling or acceptance claim — see the module docstring.
STATIC_FALLBACK = {
    "start": "ابدأ واقفًا بثبات ودع الكاميرا ترى جسمك كاملًا من الجانب.",
    "retry": "خذ نفسًا هادئًا وأعد الحركة بتمهّل مع الحفاظ على نفس الوضعية.",
    "uncertain": "اضبط وضعك بحيث يظهر كامل جسمك في الإطار ثم تابع.",
    "completed": "أتممت الحركات المطلوبة في هذه الجلسة، أحسنت الاستمرار.",
    "stopped": "أوقفت الجلسة. يمكنك البدء من جديد في أي وقت.",
}

SYSTEM_PROMPT = (
    "أنت مساعد تدريب لحركات الصلاة. مهمتك كتابة جملة عربية واحدة قصيرة "
    "(بحد أقصى عشرين كلمة) لتوجيه المتدرب في الحركة الحالية.\n"
    "قيود إلزامية:\n"
    "- لا تذكر أحكامًا شرعية ولا تصحّح صحة الصلاة ولا تجزم بالقبول أو الرفض.\n"
    "- لا تفتِ ولا تستشهد بأدلة فقهية.\n"
    "- لا تطلب بيانات شخصية ولا تخاطب شخصًا بعينه.\n"
    "- ركّز فقط على الوضعية الجسدية والحركة الحالية.\n"
    "أعد نص الجملة فقط، بدون مقدمات وبدون علامات تنصيص."
)

# Memoisation: bounded so a long-lived process cannot grow without limit.
_CACHE: dict[tuple[str, str, str], str] = {}
_CACHE_LOCK = threading.Lock()
_CACHE_MAX = 256


class PrayerGuidanceRequest(BaseModel):
    """Structured session context. Never carries frames or keypoints."""

    prayer: Literal["fajr", "dhuhr", "asr", "maghrib", "isha", "demo"]
    station: Literal[
        "standing",
        "ruku",
        "standing_after_ruku",
        "sujood_first",
        "sitting",
        "sujood_second",
        "intermediate_sitting",
        "final_sitting",
    ]
    event: Literal["start", "retry", "uncertain", "completed", "stopped"]
    rakah: int = Field(default=1, ge=1, le=10)
    station_index: int = Field(default=0, ge=0, le=200)
    total_stations: int = Field(default=1, ge=1, le=200)
    retries: int = Field(default=0, ge=0, le=1000)
    core_movements_done: int = Field(default=0, ge=0, le=1000)


class PrayerGuidanceResponse(BaseModel):
    text: str
    model: str
    degraded: bool


class PrayerGuidanceInfo(BaseModel):
    enabled: bool
    model: str
    thinking: bool


def _static_text(request: PrayerGuidanceRequest) -> str:
    return STATIC_FALLBACK[request.event]


def _build_messages(request: PrayerGuidanceRequest) -> list[dict[str, str]]:
    facts = (
        f"الصلاة: {PRAYER_AR[request.prayer]}\n"
        f"الركعة: {request.rakah}\n"
        f"الحركة الحالية: {STATION_AR[request.station]}\n"
        f"الموقف: {EVENT_AR[request.event]}\n"
        f"ترتيب الحركة: {request.station_index + 1} من {request.total_stations}\n"
        f"عدد مرات إعادة المحاولة: {request.retries}\n"
        f"عدد الحركات الأساسية المكتملة: {request.core_movements_done}"
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": facts},
    ]


def _cache_get(key: tuple[str, str, str]) -> str | None:
    with _CACHE_LOCK:
        return _CACHE.get(key)


def _cache_put(key: tuple[str, str, str], value: str) -> None:
    with _CACHE_LOCK:
        if len(_CACHE) >= _CACHE_MAX:
            _CACHE.clear()
        _CACHE[key] = value


def clear_cache() -> None:
    """Test helper — drop memoised guidance."""

    with _CACHE_LOCK:
        _CACHE.clear()


@router.get("/api/v1/prayer-guidance", response_model=PrayerGuidanceInfo)
async def prayer_guidance_info() -> PrayerGuidanceInfo:
    """Capability probe so the client can hide guidance UI when it is off."""

    settings = get_settings()
    return PrayerGuidanceInfo(
        enabled=settings.prayer_guidance_enabled,
        model=settings.deepseek_model,
        thinking=settings.deepseek_thinking,
    )


@router.post("/api/v1/prayer-guidance", response_model=PrayerGuidanceResponse)
async def prayer_guidance(request: PrayerGuidanceRequest) -> PrayerGuidanceResponse:
    """Return one short Arabic guidance sentence for the current session state."""

    settings = get_settings()

    if not settings.prayer_guidance_enabled:
        return PrayerGuidanceResponse(
            text=_static_text(request), model="static", degraded=True
        )

    key = (request.prayer, request.station, request.event)
    cached = _cache_get(key)
    if cached is not None:
        return PrayerGuidanceResponse(
            text=cached, model=settings.deepseek_model, degraded=False
        )

    try:
        text = await get_deepseek_client().complete(_build_messages(request))
    except LLMNotConfigured:
        logger.warning("Prayer guidance LLM is not configured; serving static text.")
        return PrayerGuidanceResponse(
            text=_static_text(request), model="static", degraded=True
        )
    except Exception:
        # Network, quota, timeout, provider 4xx/5xx — none of these may break
        # the prayer session, so they all degrade to static text.
        logger.exception("Prayer guidance generation failed; serving static text.")
        return PrayerGuidanceResponse(
            text=_static_text(request), model="static", degraded=True
        )

    if not text:
        logger.warning("Prayer guidance model returned empty content; using static text.")
        return PrayerGuidanceResponse(
            text=_static_text(request), model="static", degraded=True
        )

    _cache_put(key, text)
    return PrayerGuidanceResponse(
        text=text, model=settings.deepseek_model, degraded=False
    )
